connection:
    info:
      ip: ${agg_ip}
      port: ${agg_port}
      tls_config:
        enable: false
    name: FlaskConnection
    path: ibmfl.connection.flask_connection
    sync: false
data:
  info:
    npz_file: ${ibmfl_dir}/examples/datasets/mnist.npz
  name: MnistKerasDataHandler
  path: ibmfl.util.data_handlers.mnist_keras_data_handler
fusion:
  name: IterAvgFusionHandler
  path: ibmfl.aggregator.fusion.iter_avg_fusion_handler
hyperparams:
  global:
    max_timeout: 60
    num_parties: ${n_parties}
    perc_quorum: 0.75
    rounds: ${n_rounds}
    termination_accuracy: 0.9
  local:
    optimizer:
      lr: 0.01
    training:
      epochs: 100
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
